version: '3.4'
services:
  fetch:
      build:
        context: ./fetch
        # target: dev
        target: prod
      container_name: fetch
      image: dewberrycsi/nwm-fetch-forecasts:1.1.1
      privileged: true
      volumes:
        - ./fetch:/fetch