# This is a basic workflow to help you get started with Actions

name: Docker Fetch Forecast Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: docker build
      run: |
        docker build ./fetch -t dewberrycsi/nwm-fetch-forecasts:1.1.1
    - name: docker push
      run: |
        docker push dewberrycsi/nwm-fetch-forecasts:1.1.1